name: Build numstats-service

on:
    push:
        paths:
            - 'src/**'
            - 'tests/**'
            - 'Dockerfile'
            - 'Makefile'
            - '.github/workflows/numstats-service.build.yaml'
    pull_request:
        paths:
            - 'src/**'
            - 'tests/**'
            - 'Dockerfile'
            - 'Makefile'
            - '.github/workflows/numstats-service.build.yaml'

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: numstats-service
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Build image
              run: make cicd.build

            - name: Run unit tests
              run: make cicd.test.unit